#!/usr/bin/env node
/* Turn a rescued localStorage backup into Supabase (Postgres) INSERTs.
 *
 * Usage:
 *   node scripts/backup-to-sql.mjs <backup.json> [out.sql]
 *
 * Accepts the recovery-snippet export ({ cockpit: { meta, "week:...": ... } })
 * or a plain { meta, "week:...": ... } object. Emits INSERT…ON CONFLICT into
 * out.sql (default seed.sql) for the `forecast_kv` table (value is jsonb).
 * Paste the file into Supabase → SQL Editor and run it.
 *
 * seed.sql is gitignored — it holds real forecast data; keep it out of git. */
import { readFileSync, writeFileSync } from "node:fs";

const argv = process.argv.slice(2);
const replace = argv.includes("--replace");      // wipe the table first (clean slate)
const [inPath, outPath = "seed.sql"] = argv.filter((a) => !a.startsWith("--"));
if (!inPath) {
  console.error("usage: node scripts/backup-to-sql.mjs <backup.json> [out.sql] [--replace]");
  process.exit(1);
}

const parsed = JSON.parse(readFileSync(inPath, "utf8"));
const data = parsed.cockpit ?? parsed;
const updatedAt = parsed.exportedAt ?? new Date().toISOString();

const keys = Object.keys(data).filter((k) => k === "meta" || k.startsWith("week:"));
if (keys.length === 0) {
  console.error("No 'meta' or 'week:*' keys found — is this the right file?");
  process.exit(1);
}

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'"; // single-quote escape
const lines = ["-- Generated by scripts/backup-to-sql.mjs — real data, do not commit."];
if (replace) lines.push("delete from public.forecast_kv;  -- clean slate: removes any dummy/seed rows");
for (const k of keys) {
  const value = JSON.stringify(data[k]);
  lines.push(
    `INSERT INTO public.forecast_kv (key, value, updated_at) ` +
    `VALUES (${q(k)}, ${q(value)}::jsonb, ${q(updatedAt)}::timestamptz) ` +
    `ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at;`
  );
}

writeFileSync(outPath, lines.join("\n") + "\n");
console.log(`Wrote ${outPath} with ${keys.length} row(s): ${keys.join(", ")}`);
